# Generated by Django 5.0.7 on 2024-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_marca_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
